### ISSUE TITLE
> 想用两个服务器监控房间，第二个服务器monitor启动的时候一直重复启动数据连接是怎么回事

### ISSUE THREAD

**Issue by KNulL0** [yjqiang/YjMonitor#23]
> 想用两个服务器监控房间，第二个服务器monitor启动的时候一直重复启动数据连接是怎么回事

你是运行了哪个文件？具体日志如何

_Originally posted by @yjqiang in https://github.com/yjqiang/YjMonitor/issues/20#issuecomment-534400094_

**Comment by yjqiang** [comment]
？

**Comment by yjqiang** [comment]
> monitor/run.py 也没报错就是一直重复显示正在启动xxx号数据链接，不提示进入房间
房间设置大于2000就会这样，是后边的房间没开播吗

不是啊。。。一直到10000都行

**Comment by KNulL0** [comment]
> > monitor/run.py 也没报错就是一直重复显示正在启动xxx号数据链接，不提示进入房间
> > 房间设置大于2000就会这样，是后边的房间没开播吗
> 
> 不是啊。。。一直到10000都行

[2019-09-24 21:34:59] 正在启动1969号数据链接
[2019-09-24 21:34:59] 正在启动1968号数据链接
[2019-09-24 21:34:59] 正在启动1964号数据链接
当前时间为 21:35:00
Future exception was never retrieved
future: <Future finished exception=gaierror(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "C:\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
[2019-09-24 21:35:10] 正在启动1930号数据链接
Future exception was never retrieved
future: <Future finished exception=gaierror(11001, 'getaddrinfo failed')>
Traceback (most recent call last):
  File "C:\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python36\lib\socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
[2019-09-24 21:35:13] 1949号弹幕监控进入房间（2902371）

**Comment by yjqiang** [comment]
这是什么鬼报错  你更新python到3.7.4试试  我这里完全正常

**Comment by yjqiang** [comment]
你设置成start0 end5 看看还有没有报错…… 这么远的数据log  源头都找不到

**Comment by KNulL0** [comment]
> 你设置成start0 end5 看看还有没有报错…… 这么远的数据log 源头都找不到

3.7也这样，房间设置小就没问题了。server服务器的问题吗

**Comment by yjqiang** [comment]
不是啊 我们都是4000房间的  你自己出问题了

**Comment by lovezm** [comment]
问个zz问题 -- 创建好了key  填在哪里= =

**Comment by KNulL0** [comment]
[Errno 104] Connection reset by peer
[2019-11-21 18:20:30] 465号数据连接异常或主动断开，正在处理剩余信息
[2019-11-21 18:20:30] 465号数据连接退出，剩余任务处理完毕
[2019-11-21 18:20:30] 正在启动465号数据链接
[Errno 104] Connection reset by peer
[2019-11-21 18:20:30] 3445号数据连接异常或主动断开，正在处理剩余信息
[2019-11-21 18:20:30] 3445号数据连接退出，剩余任务处理完毕
[2019-11-21 18:20:30] 正在启动3445号数据链接
[Errno 104] Connection reset by peer
这是什么报错。。

**Comment by yjqiang** [comment]
网络问题
