### ISSUE TITLE
monitor 的问题

### ISSUE THREAD

**Issue by yuban10703** [yjqiang/YjMonitor#33]
[3b+_2020-02-11_21-46-35.log](https://github.com/yjqiang/YjMonitor/files/4186165/3b%2B_2020-02-11_21-46-35.log)
![image](https://user-images.githubusercontent.com/39484884/74245365-d9b30580-4d1d-11ea-921d-10a9667438db.png)
这个值超过1000貌似就会这样
![ZY_GFNHBE{YD3E@7 P2IO%C](https://user-images.githubusercontent.com/39484884/74245448-f9e2c480-4d1d-11ea-9c23-f58fd4e91acf.png)

**Comment by yjqiang** [comment]
这个真的不好判定，我觉得你开多了，你试试4000，正常我们都是 4000 的

**Comment by yjqiang** [comment]
如果你能正常开几百在你电脑上运行，开几千就报错，只有可能是电脑性能问题，或者linux奇怪的一些约束。

**Comment by yuban10703** [comment]
emmm,不知道什么原因超过1000好像就会这样,
![image](https://user-images.githubusercontent.com/39484884/74247474-116f7c80-4d21-11ea-88c7-0d976b47961c.png)
电脑性能肯定是没问题的
我去试试windows

**Comment by yjqiang** [comment]
linux文件之类的有自己的一套约束。

**Comment by yjqiang** [comment]
或者你python版本问题？https://github.com/yjqiang/YjMonitor/blob/master/monitor/danmu/conn.py#L52 这里你设置打印详细看看。https://blog.csdn.net/handsomekang/article/details/9373035

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/74249610-6234a480-4d24-11ea-9af7-5e09bd919881.png)
用的自带的python,
我去试试

**Comment by yuban10703** [comment]
[2020-02-11 23:19:56] 正在启动1059号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1045号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1089号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1083号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1094号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1080号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1012号数据链接
Traceback (most recent call last):
  File "/home/yuban10703/YjMonitor/monitor/danmu/conn.py", line 49, in open
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
  File "/usr/lib/python3.7/asyncio/streams.py", line 77, in open_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 905, in create_connection
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1275, in _ensure_resolved
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
OSError: [Errno 22] Invalid argument
[2020-02-11 23:19:56] 正在启动1084号数据链接


emmmmmmmm

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/74250373-762cd600-4d25-11ea-9842-10dd7f5e6230.png)

**Comment by yjqiang** [comment]
你先试试windows吧，然后再试试linux升级python3.8.1看看

**Comment by yuban10703** [comment]
我试试..

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/74250865-3a464080-4d26-11ea-8972-202198a5279c.png)
正常了.........不过win的python是3.8.1

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/74252045-079d4780-4d28-11ea-86e9-a0b0459f4dc6.png)
Linux换了3.8还是不行
emmmmm

**Comment by yjqiang** [comment]
诡异问题。。。看来python或者linux锅了。我close啦？

**Comment by yuban10703** [comment]
ok
